version: '3'

services:
  revive:
    image: revive-adserver/revive:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=revive-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=revive
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=revive
    depends_on:
      - revive-mysql
    volumes:
      - revive-data:/var/www/html/var

  revive-mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD=rootpassword
      MYSQL_DATABASE=revive
      MYSQL_USER=revive
      MYSQL_PASSWORD=password
    volumes:
      - revive-mysql-data:/var/lib/mysql

volumes:
  revive-data:
  revive-mysql-data:
