version: '3'

services:
  revive:
    image: krish512/revive:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      REVIVE_DB_HOST: revive-mysql
      REVIVE_DB_PORT: 3306
      REVIVE_DB_USER: revive
      REVIVE_DB_PASSWORD: password
      REVIVE_DB_DATABASE: revive
      REVIVE_DOMAIN: localhost:8081
    depends_on:
      - revive-mysql
    volumes:
      - revive-data:/var/www/html/var

  revive-mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: revive
      MYSQL_USER: revive
      MYSQL_PASSWORD: password
    volumes:
      - revive-mysql-data:/var/lib/mysql

volumes:
  revive-data:
  revive-mysql-data:
